------------------------------------------
--DDL statement for table 'HR' database--
--------------------------------------------

-- Drop the tables in case they exist

DROP TABLE CENSUS_DATA;
DROP TABLE CHICAGO_PUBLIC_SCHOOLS;
DROP TABLE CHICAGO_CRIME_DATA;

-- Create the tables

CREATE TABLE CENSUS_DATA (								

                          COMMUNITY_AREA_NUMBER CHAR(9) NOT NULL,
                          COMMUNITY_AREA_NAME VARCHAR(25) NOT NULL,
                          PERCENT_OF_HOUSING_CROWDED DECIMAL(10,2),
                          PERCENT_HOUSEHOLDS_BELOW_POVERTY DECIMAL(10,2),
                          PERCENT_AGED_16__UNEMPLOYED DECIMAL(10,2),
                          PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA DECIMAL(10,2),
                          PERCENT_AGED_UNDER_18_OR_OVER_64 DECIMAL(10,2),
                          PER_CAPITA_INCOME DECIMAL(10,2),
                          HARDSHIP_INDEX DECIMAL(10,2)
                        );

 CREATE TABLE CHICAGO_PUBLIC_SCHOOLS (
	"School_ID"	INTEGER,
	"NAME_OF_SCHOOL"	TEXT,
	"ElementaryMiddleorHighSchool"	TEXT,
	"Street_Address"	TEXT,
	"City"	TEXT,
	"State"	TEXT,
	"ZIP_Code"	INTEGER,
	"Phone_Number"	TEXT,
	"Link"	TEXT,
	"Network_Manager"	TEXT,
	"Collaborative_Name"	TEXT,
	"Adequate_Yearly_Progress_Made_"	TEXT,
	"Track_Schedule"	TEXT,
	"CPS_Performance_Policy_Status"	TEXT,
	"CPS_Performance_Policy_Level"	TEXT,
	"HEALTHY_SCHOOL_CERTIFIED"	TEXT,
	"Safety_Icon"	TEXT,
	"SAFETY_SCORE"	INTEGER,
	"Family_Involvement_Icon"	TEXT,
	"Family_Involvement_Score"	TEXT,
	"Environment_Icon"	TEXT,
	"Environment_Score"	INTEGER,
	"Instruction_Icon"	TEXT,
	"Instruction_Score"	INTEGER,
	"Leaders_Icon"	TEXT,
	"Leaders_Score"	TEXT,
	"Teachers_Icon"	TEXT,
	"Teachers_Score"	TEXT,
	"Parent_Engagement_Icon"	TEXT,
	"Parent_Engagement_Score"	TEXT,
	"Parent_Environment_Icon"	TEXT,
	"Parent_Environment_Score"	TEXT,
	"AVERAGE_STUDENT_ATTENDANCE"	TEXT,
	"Rate_of_Misconducts__per_100_students_"	REAL,
	"Average_Teacher_Attendance"	TEXT,
	"Individualized_Education_Program_Compliance_Rate"	TEXT,
	"Pk_2_Literacy__"	TEXT,
	"Pk_2_Math__"	TEXT,
	"Gr3_5_Grade_Level_Math__"	TEXT,
	"Gr3_5_Grade_Level_Read__"	TEXT,
	"Gr3_5_Keep_Pace_Read__"	TEXT,
	"Gr3_5_Keep_Pace_Math__"	TEXT,
	"Gr6_8_Grade_Level_Math__"	TEXT,
	"Gr6_8_Grade_Level_Read__"	TEXT,
	"Gr6_8_Keep_Pace_Math_"	TEXT,
	"Gr6_8_Keep_Pace_Read__"	TEXT,
	"Gr_8_Explore_Math__"	TEXT,
	"Gr_8_Explore_Read__"	TEXT,
	"ISAT_Exceeding_Math__"	TEXT,
	"ISAT_Exceeding_Reading__"	TEXT,
	"ISAT_Value_Add_Math"	TEXT,
	"ISAT_Value_Add_Read"	TEXT,
	"ISAT_Value_Add_Color_Math"	TEXT,
	"ISAT_Value_Add_Color_Read"	TEXT,
	"Students_Taking__Algebra__"	TEXT,
	"Students_Passing__Algebra__"	TEXT,
	"9thGradeEXPLORE(2009)"	TEXT,
	"9thGradeEXPLORE(2010)"	TEXT,
	"10thGradePLAN(2009)"	TEXT,
	"10thGradePLAN(2010)"	TEXT,
	"Net_Change_EXPLORE_and_PLAN"	TEXT,
	"11thGradeAverageACT(2011)"	TEXT,
	"Net_Change_PLAN_and_ACT"	TEXT,
	"College_Eligibility__"	TEXT,
	"Graduation_Rate__"	TEXT,
	"College_Enrollment_Rate__"	TEXT,
	"COLLEGE_ENROLLMENT"	INTEGER,
	"General_Services_Route"	INTEGER,
	"Freshman_on_Track_Rate__"	TEXT,
	"X_COORDINATE"	REAL,
	"Y_COORDINATE"	REAL,
	"Latitude"	REAL,
	"Longitude"	REAL,
	"COMMUNITY_AREA_NUMBER"	INTEGER,
	"COMMUNITY_AREA_NAME"	TEXT,
	"Ward"	INTEGER,
	"Police_District"	INTEGER,
	"Location"	TEXT
);

CREATE TABLE "CHICAGO_CRIME_DATA" (
	"ID"	INTEGER,
	"CASE_NUMBER"	TEXT,
	"DATE"	TEXT,
	"BLOCK"	TEXT,
	"IUCR"	INTEGER,
	"PRIMARY_TYPE"	TEXT,
	"DESCRIPTION"	TEXT,
	"LOCATION_DESCRIPTION"	TEXT,
	"ARREST"	TEXT,
	"DOMESTIC"	TEXT,
	"BEAT"	INTEGER,
	"DISTRICT"	INTEGER,
	"WARD"	INTEGER,
	"COMMUNITY_AREA_NUMBER"	INTEGER,
	"FBICODE"	INTEGER,
	"X_COORDINATE"	INTEGER,
	"Y_COORDINATE"	INTEGER,
	"YEAR"	INTEGER,
	"LATITUDE"	REAL,
	"LONGITUDE"	REAL,
	"LOCATION"	TEXT
);